// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Online.Payment.Ghabz.Repository.DbContexts;

namespace Online.Payment.Ghabz.Migrations
{
    [DbContext(typeof(OnlinePaymentGhabzDbContext))]
    [Migration("20190426170041_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Online.Payment.Ghabz.Repository.Models.GhabzHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Price");

                    b.Property<string>("ShenaseGhabz")
                        .IsRequired();

                    b.Property<string>("ShenasePardakht");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("ghabzHistories");
                });

            modelBuilder.Entity("Online.Payment.Ghabz.Repository.Models.PaymentHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("GhabzHistoryId");

                    b.Property<bool>("IsPayment");

                    b.Property<string>("TrakingNumber")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("GhabzHistoryId");

                    b.ToTable("paymentHistories");
                });

            modelBuilder.Entity("Online.Payment.Ghabz.Repository.Models.PaymentHistory", b =>
                {
                    b.HasOne("Online.Payment.Ghabz.Repository.Models.GhabzHistory", "GhabzHistory")
                        .WithMany()
                        .HasForeignKey("GhabzHistoryId");
                });
#pragma warning restore 612, 618
        }
    }
}
